### ISSUE TITLE
0.3 每一句都出现Download Vocos from huggingface charactr/vocos-mel-24khz

### ISSUE THREAD

**Issue by lin16303** [jianchang512/f5-tts-api#5]
如果挂梯子就会快速跳过，如果不挂梯子就会卡在Download Vocos from huggingface charactr/vocos-mel-24khz，超时跳过，极大拖慢了配音速度
INFO:__main__:Accessing generate_audio route
INFO:__main__:Processing audio file: audio
Download Vocos from huggingface charactr/vocos-mel-24khz
Converting audio...
Using custom reference text...
ref_text   你好啊我亲爱的朋友，希望你的每一天都是美好愉快的.
Voice: main
Ref_audio: C:\Users\Alex\AppData\Local\Temp\tmp_x9bnwub.wav
Ref_text: 你好啊我亲爱的朋友，希望你的每一天都是美好愉快的.
No voice tag found, using main.
Voice: main
gen_text 0 你好啊，我亲爱的朋友，希望你的每一天都是美好愉快的！
Generating audio in 1 batches...
100%|███████████████████████████████████████████████| 1/1 [00:01<00:00,  1.79s/it]
wave_path='D:/gpt4all/F5-TTS-gpu-0.3/tmp/out-1732003413.3682363.wav'
D:/gpt4all/F5-TTS-gpu-0.3/tmp/out-1732003413.3682363.wav

**Comment by jianchang512** [comment]
api.py 里这个位置False改为True
其实没那么长时间影响，仅检测本地是否存在，存在则跳过

![IMG_20241119_193943.jpg](https://github.com/user-attachments/assets/97d5ba2f-ade8-4413-9608-c9612e8e0d1c)

**Comment by lin16303** [comment]
改成true出错
INFO:__main__:Accessing generate_audio route
INFO:__main__:Processing audio file: audio
Load vocos from local path ./checkpoints/vocos-mel-24khz
ERROR:__main__:Error generating audio: [Errno 2] No such file or directory: './checkpoints/vocos-mel-24khz/config.yaml'
Traceback (most recent call last):
  File "D:\gpt4all\F5-TTS-gpu-0.3\api.py", line 134, in api
    vocoder = load_vocoder(vocoder_name=vocoder_name, is_local=True, local_path=vocoder_local_path)
  File "D:\gpt4all\F5-TTS-gpu-0.3\runtime\..\f5_tts\infer\utils_infer.py", line 104, in load_vocoder
    vocoder = Vocos.from_hparams(config_path)
  File "D:\gpt4all\F5-TTS-gpu-0.3\runtime\./Lib/site-packages\vocos\pretrained.py", line 54, in from_hparams
    with open(config_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/vocos-mel-24khz/config.yaml'

**Comment by jianchang512** [comment]
`vocoder = load_vocoder(vocoder_name=vocoder_name, is_local=True, local_path=vocoder_local_path)`

改成这样试试
```
vocoder = load_vocoder(vocoder_name=vocoder_name, is_local=True, local_path='./modelscache/hub/models--charactr--vocos-mel-24khz/snapshots/0feb3fdd929bcd6649e0e7c5a688cf7dd012ef21/')

```

**Comment by lin16303** [comment]
行了，谢谢
